apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-patient-service
  template:
    metadata:
      labels:
        app: clinic-patient-service
    spec:
      containers:
        - name: clinic-patient-service
          image: your-registry/clinic-patient-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://127.0.0.1:3306/patient_db?useSSL=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
